# Service ID
add_exception:
  # Service name as shown in UI
  name: Add exception
  # Description of the service
  description: Add an exception to the schedule
  target:
    entity:
      integration: thermosmart
      domain: climate
  # Different fields that your service accepts
  fields:
    start_day:
      # Field name as shown in UI
      name: Start day
      description: Day at with the exception starts [1-31].
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: 1
      # The default field value
      default: 1
      # Selector
      selector:
        number:
          min: 1
          max: 31
    start_month:
      # Field name as shown in UI
      name: Start month
      description: Month at with the exception starts [1-12].
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: 1
      # The default field value
      default: 1
      # Selector
      selector:
        number:
          min: 1
          max: 12
    start_year:
      # Field name as shown in UI
      name: Start year
      description: Year at with the exception starts.
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: 2021
      # The default field value
      default: 2021
      # Selector
      selector:
        number:
    start_time:
      # Field name as shown in UI
      name: Start time
      description: Time at with the exception starts.
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: '12:00:00'
      # The default field value
      default: '12:00:00'
      # Selector
      selector:
        time:
    end_day:
      # Field name as shown in UI
      name: End day
      description: Day at with the exception ens [1-31].
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: 1
      # The default field value
      default: 1
      # Selector
      selector:
        number:
          min: 1
          max: 31
    end_month:
      # Field name as shown in UI
      name: End month
      description: Month at with the exception ends [1-12].
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: 1
      # The default field value
      default: 1
      # Selector
      selector:
        number:
          min: 1
          max: 12
    end_year:
      # Field name as shown in UI
      name: End year
      description: Year at with the exception ends.
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: 2021
      # The default field value
      default: 2021
      # Selector
      selector:
        number:
    end_time:
      # Field name as shown in UI
      name: End time
      description: Time at with the exception ends.
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: '12:00:00'
      # The default field value
      default: '12:00:00'
      # Selector
      selector:
        time:
    program:
      # Field name as shown in UI
      name: Program
      description: Name of the program
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: 'home'
      # The default field value
      default: 'home'
      # Selector
      selector:
        select:
          options:
            - anti_freeze
            - not_home
            - home
            - comfort

clear_exceptions:
  # Service name as shown in UI
  name: Clear exceptions
  # Description of the service
  description: Clear exceptions to the schedule
  target:
    entity:
      integration: thermosmart
      domain: climate